cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'carthage'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask '1password'
cask 'adobe-creative-cloud'
cask 'atom'
cask 'emojipedia'
cask 'firefox'
cask 'google-chrome'
cask 'p4merge'
cask 'paw'
cask 'pixelstick'
cask 'psequel'
cask 'screenhero'
cask 'sequel-pro'
cask 'sketch'
cask 'slack'
cask 'sourcetree'
cask 'spotify'
cask 'steam'
cask 'tunnelbear'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'
